name: tcrl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=1.9
  - pytorch::torchvision
  - nvidia::cudatoolkit=11.1
  - pip
  - pip:
    - hydra-core==1.3.0
    - gym==0.21.0
    - dm-control==1.0.9
    - wandb==0.13.7
    - matplotlib==3.5.0
    - moviepy
    - imageio
    - termcolor
    - ipdb
    - pandas